export { default as CreateCustomer } from "./customer/CreateCustomer"
export { default as LoginCustomer } from "./customer/LoginCustomer"
export { default as ForgotPasswordCustomerStep1 } from "./customer/ForgotPasswordCustomerStep1"
export { default as ForgotPasswordCustomerStep2 } from "./customer/ForgotPasswordCustomerStep2"
export {default as HomeCustomer} from "./customer/HomeCustomer"
export {default as ProfileCustomer} from "./customer/ProfileCustomer"
export {default as PointsCustomer} from "./customer/PointsCustomer"
export {default as UpdatePasswordCustomer} from "./customer/UpdatePasswordCustomer"
export {default as DisabledAccountCustomer} from "./customer/DisabledAccountCustomer"

export { default as CreateConsulant } from "./consulants/CreateConsulant"
export { default as LoginConsulant } from "./consulants/LoginConsulant"
export { default as ForgotPasswordConsulantStep1 } from "./consulants/ForgotPasswordConsulantStep1"
export { default as ForgotPasswordConsulantStep2 } from "./consulants/ForgotPasswordConsulantStep2"
export {default as HomeConsulant} from "./consulants/HomeConsulant"
export {default as ProfileConsulant} from "./consulants/ProfileConsulant"
export {default as CreateOrder} from "./consulants/CreateOrder"
export {default as PointsConsulant} from "./consulants/PointsConsulant"
export {default as UpdateStoreConsulant} from "./consulants/UpdateStoreConsulant"
export {default as UpdatePasswordConsulant} from "./consulants/UpdatePasswordConsulant"
export {default as DisabledAccountConsulant} from "./consulants/DisabledAccountConsulant"


export { default as CreateStore } from "./store/CreateStore"
export { default as LoginStore } from "./store/LoginStore"
export { default as ForgotPasswordStoretStep1 } from "./store/ForgotPasswordStoreStep1"
export { default as ForgotPasswordStoreStep2 } from "./store/ForgotPasswordStoreStep2"
export {default as HomeStore} from "./store/HomeStore"
export {default as ProfileStore} from "./store/ProfileStore"
export {default as PointsStore} from "./store/PointsStore"
export {default as UpdatePasswordStore} from "./store/UpdatePasswordStore"
export {default as DisabledAccountStore} from "./store/DisabledAccountStore"



export { default as LoginAdmin } from "./adm/LoginAdmin"
export { default as CreateAdminStep1 } from "./adm/CreateAdminStep1"
export { default as CreateAdminStep2 } from "./adm/CreateAdminStep2"
export { default as HomeAdmin } from "./adm/HomeAdmin"
export { default as ProfileAdmin } from "./adm/ProfileAdmin"
export { default as DeleteAccountAdmin } from "./adm/DeleteAccountAdmin"
export { default as UpdatePasswordAdmin } from "./adm/UpdatePasswordAdmin"
export { default as ForgotPasswordAdminStep1 } from "./adm/ForgotPasswordAdminStep1"
export { default as ForgotPasswordAdminStep2 } from "./adm/ForgotPasswordAdminStep2"
export { default as AdminCustomers } from "./adm/AdminCustomers"
export { default as AdminCustomersEdit } from "./adm/AdminCustomersEdit"
export { default as AdminStores } from "./adm/AdminStores"
export { default as AdminStoresEdit } from "./adm/AdminStoresEdit"
export { default as AdminConsulants } from "./adm/AdminConsulants"
export { default as AdminConsulantsEdit } from "./adm/AdminConsulantsEdit"
export { default as PointsAdmin } from "./adm/PointsAdmin"
export { default as PointsAdminShow } from "./adm/PointsAdminShow"
export { default as PointsAdminPending } from "./adm/PointsAdminPending"
export { default as PointsAdminChose } from "./adm/PointsAdminChose"
export { default as PointsAdminCreate } from "./adm/PointsAdminCreate"
export { default as PointsAdminConsulant } from "./adm/PointsAdminConsulant"
export { default as PointsAdminConsulantOrders } from "./adm/PointsAdminConsulantOrders"
export { default as PointsAdminCustomer } from "./adm/PointsAdminCustomer"
export { default as PointsAdminCustomersOrders } from "./adm/PointsAdminCustomersOrders"
export { default as PointsAdminStore } from "./adm/PointsAdminStore"
export { default as PointsAdminStoreOrders } from "./adm/PointsAdminStoreOrders"
export { default as PointsAdminCustomerDecrease } from "./adm/PointsAdminCustomerDecrease"
export { default as PointsAdminConsulantDecrease } from "./adm/PointsAdminConsulantDecrease"



export { default as homeLanding } from "./landing/HomeLanding"
export { default as About } from "./landing/About"
export { default as MeetPartners} from "./landing/MeetPartners"
export { default as Award} from "./landing/Award"

